export const profile = {
  name: 'Dammar B.K.',
  title: 'SOFTWARE ENGINEER',
  intro: 'Hii, I’m Dammar B.K.',
  tagline: 'Turning Ideas Into Digital Solutions.',
  altTagline: 'Build. Solve. Innovate.',
  professionalTitle: 'FULL-STACK DEVELOPER • WEB DEVELOPER • NETWORKING & TECHNOLOGY',
  bio: 'I build modern, responsive and scalable web applications by combining frontend development, backend engineering, databases, networking and problem-solving.',
  about: `I am Dammar B.K., a Software Engineer interested in software development, full-stack web development, networking, databases, multimedia technology and solving real-world problems through technology. I enjoy turning ideas into practical digital products that are useful, reliable and user-friendly.`,
  careerGoal: 'To build reliable, scalable and user-friendly software solutions while continuously improving my technical skills and contributing to meaningful projects.',
  email: 'bishwokarmadaniel9@gmail.com',
  phone: '9868636008',
  location: 'Your City, Country',
  github: 'https://github.com/',
  linkedin: 'https://www.linkedin.com/',
  facebook: 'https://www.facebook.com/share/18s6JvwWyo/',
  instagram: 'https://www.instagram.com/',
  tiktok: 'https://www.tiktok.com/',
  cv: '/cv.html',
  profileImage: '/images/myl.jpg',
  navItems: [
    'Home',
    'About',
    'Skills',
    'Services',
    'Projects',
    'College Projects',
    'Websites',
    'Experience',
    'Education',
    'Certifications',
    'Resume',
    'Contact',
  ],
}

export default profile
